# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180424_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
