# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180424_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='img_cover',
            field=models.ImageField(null=True, upload_to='adver-img-covers/'),
        ),
        migrations.AddField(
            model_name='category',
            name='img_header',
            field=models.ImageField(null=True, upload_to='category-img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_cover',
            field=models.ImageField(null=True, upload_to='post-img-covers/'),
        ),
    ]
