# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180426_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='img_header',
            new_name='img_cover',
        ),
    ]
