# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_course_workshop_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_workshop',
            name='Finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='Finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course_workshop',
            name='HomePage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course_workshop',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='HomePage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
